name: native_opencv
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.converus.native_opencv
        pluginClass: NativeOpencvPlugin
      ios:
        pluginClass: NativeOpencvPlugin
  assets:
    - packages/native_opencv/assets/haarcascade_eye_tree_eyeglasses.xml
  